portal/urls.py
from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt

from django.contrib.sitemaps.views import sitemap

# from portal.views import FaqsView
# from portal.views import CareersView
from portal.views import AboutView, RecordCallEnquiryView
from portal.views import ContactView
from portal.views import ListVenueView
from portal.views import DetailView
from portal.views import HomeView, LocationsListView
from portal.views import LandlordView
from portal.views import HowitWorks
from portal.views import PolicyView
from portal.views import RegisterView
from portal.views import SearchView
from portal.views import SellForAFixedFee
# from portal.views import TermsView
from portal.views import WhatsIncluded
from portal.views import AgentsView
from portal.views import AgentsDetailView
from portal.views import PlansView
from portal.views import WhyUsView
from portal.views import CancellationPolicyView
from portal.views import RentForAFixedFeeView
from portal.views import FormSubmittedView

from portal.sitemaps import ListingSitemap, BlogSitemap

app_name = 'portal'

sitemaps = {
    'properties': ListingSitemap,
    'blogs': BlogSitemap,
}

urlpatterns = [
    path('', HomeView.as_view(), name="portal-home"),
    path('landlords/', LandlordView.as_view(), name="portal-landlords"),

    re_path(r"^s/$", SearchView.as_view(), name="portal-search"),
    re_path(r'^s/(?P<category>(serviced-offices|banquet-halls|coworking-spaces|meeting-rooms))/$',
        SearchView.as_view(),
        kwargs={
            'sef': True
        }, name='search-by-category'),
    re_path(r'^s/(?P<category>(serviced-offices|banquet-halls|coworking-spaces|meeting-rooms))/(?P<city>[a-z0-9\-]+)/$',
        SearchView.as_view(),
        kwargs={
            'sef': True
        }),
    re_path(r'^s/(?P<category>(serviced-offices|banquet-halls|coworking-spaces|meeting-rooms))/(?P<city>[a-z0-9\-]+)/'
        r'(?P<location>[a-z0-9\-]+)/$',
        SearchView.as_view(),
        kwargs={
            'sef': True
        }),
    re_path(r'^s/(?P<category>(serviced-offices|banquet-halls|coworking-spaces|meeting-rooms))/(?P<city>[a-z0-9\-]+)/'
        r'(?P<location>[a-z0-9\-]+)/(?P<sublocation>[a-z0-9\-]+)/$',
        SearchView.as_view(),
        kwargs={
            'sef': True
        }),

    re_path(r'^s/(?P<city>[a-z0-9\-]+)/$',
        SearchView.as_view(),
        kwargs={
            'sef': True
        }),
    re_path(r'^s/(?P<city>[a-z0-9\-]+)/(?P<location>[a-z0-9\-]+)/$',
        SearchView.as_view(),
        kwargs={
            'sef': True
        }),
    re_path(r'^s/(?P<city>[a-z0-9\-]+)/(?P<location>[a-z0-9\-]+)/'
        r'(?P<sublocation>[a-z0-9\-]+)/$',
        SearchView.as_view(),
        kwargs={
            'sef': True
        }),

    # re_path(r'(?P<venue_type>(business-center|hotels))/(?P<category>(serviced-offices|banquet-halls|coworking-spaces|meeting-rooms))/(?P<slug>[^/]+)-(?P<pk>\d+)/', DetailView.as_view(), name="portal-detail"),
    re_path(r'(?P<category>(serviced-offices|banquet-halls|coworking-spaces|meeting-rooms))/(?P<slug>[^/]+)-(?P<pk>\d+)/', DetailView.as_view(), name="portal-detail"),
    re_path(r'(?P<slug>[^/]+)-(?P<pk>\d+)/', DetailView.as_view(), name="portal-detail"),
    path('register/', RegisterView.as_view(), name="register"),

    re_path(r'agents/(?P<pk>\d+)/', AgentsDetailView.as_view(), name="agents-detail"),
    path('agents/', AgentsView.as_view(), name="agents"),

    # Sell Menu Urls
    path('sell/sell-for-a-fixed-fee/', SellForAFixedFee.as_view(), name="sell-for-a-fixed-fee"),
    path('sell/how-it-works/', HowitWorks.as_view(), name="sell-how-it-works"),
    path('sell/whats-included/', WhatsIncluded.as_view(), name="whats-included"),

    # Rent Menu Urls
    path('why-list-with-us/', WhyUsView.as_view(), name="why-us"),
    path('rent/rent-for-a-fixed-fee/', RentForAFixedFeeView.as_view(), name="rent-for-a-fixed-fee"),
    path('rent/how-it-works/', HowitWorks.as_view(), name="rent-how-it-works"),

    # Original
    path('about', AboutView.as_view(), name="about"),
    # path('terms-and-conditions', TermsView.as_view(), name="terms"),
    path('privacy-policy', PolicyView.as_view(), name="policy"),
    path('contact', ContactView.as_view(), name="contact"),
    path('cancellation-policy', CancellationPolicyView.as_view(), name="cancellation-policy"),
    path('list-your-space', ListVenueView.as_view(), name="list-space"),

    re_path(r'f/s/(?P<type>[^/]+)/', FormSubmittedView.as_view(), name="form-submitted"),

    path('record-call/<int:pk>/', csrf_exempt(RecordCallEnquiryView.as_view()), name='record-call'),
    path('locations/', LocationsListView.as_view(), name='locations-list'),
    path('plans/buy/', PlansView.as_view(), name='plans-buy'),

    # the sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

shapp/urls.py
"""shapp URL Configuration"""
from django.urls import path
from django.urls import include
from django.contrib import admin


urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('', include('portal.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('speedyblog.urls')),
    # Third party library
    path('s3direct/', include('s3direct.urls')),
    # path('admin/runas/', include('runas.urls')),
]

speedyblog/urls.py
from django.urls import re_path

from speedyblog.views import BlogCategoryView
from speedyblog.views import BlogDetailView
from speedyblog.views import BlogListView


app_name = "speedyblog"

urlpatterns = [
    re_path(
        r'^(?P<slug>[-_\w]+)/$',
        BlogDetailView.as_view(),
        name='blog_detail'
    ),
    re_path(r'^category/(?P<slug>[-_\w]+)/$', BlogCategoryView.as_view(), name='blog_category'),
    re_path(r'^$', BlogListView.as_view(), name='blog_index'),
]

speedyblog/models.py
from django.conf import settings
from django.urls import reverse

from django.db import models

from s3direct.fields import S3DirectField

from .settings import COMMENT_STATUS_PENDING, COMMENT_STATUS_APPROVED, COMMENT_STATUS_DELETED
from .settings import POST_STATUS_PUBLISHED, POST_STATUS_UNPUBLISHED, POST_STATUS_DRAFT


class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField()

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    meta_title = models.CharField(max_length=100, blank=True)
    meta_description = models.CharField(max_length=500, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_meta_title(self):
        return self.meta_title or self.name

    def get_meta_description(self):
        return self.meta_description

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }

        return reverse('speedyblog:blog_category', kwargs=kwargs)

    def get_posts_count(self):
        return Post.objects.filter(category=self, status=POST_STATUS_PUBLISHED).count()


class Post(models.Model):
    STATUSES = (
        (POST_STATUS_PUBLISHED, 'Published'),
        (POST_STATUS_UNPUBLISHED, 'Unpublished'),
        (POST_STATUS_DRAFT, 'Draft'),
    )

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    status = models.CharField(max_length=1, choices=STATUSES, default=POST_STATUS_PUBLISHED, db_index=True)

    image = S3DirectField(dest="user_assets", blank=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    meta_title = models.CharField(max_length=100, blank=True)
    meta_description = models.CharField(max_length=500, blank=True)

    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    allow_comments = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.title

    def get_meta_title(self):
        return self.meta_title or self.title

    def get_meta_description(self):
        return self.meta_description or self.description

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }

        return reverse('speedyblog:blog_detail', kwargs=kwargs)

    def get_comments_count(self):
        return Comment.objects.filter(post=self, status=COMMENT_STATUS_APPROVED).count()


class Comment(models.Model):
    STATUSES = (
        (COMMENT_STATUS_PENDING, 'Pending'),
        (COMMENT_STATUS_APPROVED, 'Approved'),
        (COMMENT_STATUS_DELETED, 'Deleted')
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()

    created_on = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField(default='0.0.0.0')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=50, default='anonymous')
    user_email = models.EmailField(blank=True)

    status = models.CharField(max_length=1, choices=STATUSES, default=COMMENT_STATUS_PENDING, db_index=True)

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        ordering = ['created_on']

speedyblog/forms.py
from django import forms

from speedyblog.models import Comment
from speedyblog.settings import SPEEDY_POST_MAX_LENGTH


class UserCommentForm(forms.ModelForm):
    comment = forms.CharField()

    class Meta:
        model = Comment
        fields = ["comment"]
        widgets = {
            'comment': forms.Textarea(attrs={'maxlength': SPEEDY_POST_MAX_LENGTH})
        }

    def clean_comment(self):
        comment = self.cleaned_data.get('comment')

        if comment:
            if not comment.strip():
                raise forms.ValidationError('Comment field is required.')

        return comment


class CommentForm(UserCommentForm):
    user_name = forms.CharField(label='Username')
    user_email = forms.EmailField(label='Email', required=False)

    class Meta:
        model = Comment
        fields = ("user_name", "user_email", "comment")
        widgets = {
            'comment': forms.Textarea(attrs={'maxlength': SPEEDY_POST_MAX_LENGTH})
        }

    def clean_user_name(self):
        user_name = self.cleaned_data.get('user_name')

        if user_name:
            if not user_name.strip():
                raise forms.ValidationError('Username is required.')

        return user_name

speedyblog/views.py
import requests

from django.http import Http404
from django.conf import settings
from django.urls import reverse
from django.shortcuts import redirect
from django.views.generic.dates import DateDetailView
from django.views.generic import TemplateView, DetailView

from speedyblog.forms import CommentForm
from speedyblog.models import Comment, Post, Category

from shapp.helpers import get_client_ip

from speedyblog.settings import COMMENT_STATUS_APPROVED, POST_STATUS_PUBLISHED


class BlogListView(TemplateView):
    template_name = 'speedyblog/post_list_page.html'

    def get_context_data(self, **kwargs):
        ctx = super(BlogListView, self).get_context_data(**kwargs)

        ctx['posts'] = Post.objects.filter(status=POST_STATUS_PUBLISHED).select_related().order_by('-created_on')
        ctx['categories'] = Category.objects.all().order_by('name')

        return ctx


class BlogCategoryView(TemplateView):
    template_name = 'speedyblog/post_list_page.html'

    def get_context_data(self, **kwargs):
        slug = kwargs['slug']
        try:
            category = Category.objects.get(slug=slug)
        except Category.DoesNotExists:
            raise Http404()

        ctx = super(BlogCategoryView, self).get_context_data(**kwargs)
        ctx['posts'] = Post.objects.filter(status=POST_STATUS_PUBLISHED, category=category).select_related()
        ctx['selected_category'] = category
        ctx['categories'] = Category.objects.all().order_by('name')

        return ctx


class BlogDetailView(DetailView):
    model = Post
    field_name = 'slug'
    page_template = "speedyblog/post_detail_page.html"

    def get_queryset(self):
        queryset = super(BlogDetailView, self).get_queryset()

        return queryset.select_related()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        post = self.object

        form = CommentForm(request.POST)

        context = self.get_context_data(object=post)
        context['comment_form'] = form

        if form.is_valid():

            if not self.verify_captcha(request):
                context['invalid_captcha'] = True
                return self.render_to_response(context)

            comment = form.save(commit=False)
            comment.post = post

            comment.ip = get_client_ip(request)
            comment.save()

            return redirect("{}?success=1".format(post.get_absolute_url()))

        return self.render_to_response(context)

    def verify_captcha(self, request):
        payload = {
            'response': request.POST['g-recaptcha-response'],
            'remoteip': get_client_ip(request),
            'secret': settings.CAPTCHA_SECRET_KEY
        }

        response = requests.post('https://www.google.com/recaptcha/api/siteverify', payload)

        if response.status_code == 200:
            response = response.json()
        else:
            return False

        return response['success']

    def get_context_data(self, **kwargs):
        form = CommentForm()

        context = {
            'page_template': self.page_template,
            'comment_form': form,
            'categories': Category.objects.all().order_by('name'),
            'post_url': '{}{}'.format(settings.BASE_URL, self.object.get_absolute_url()),
            'comments': Comment.objects.filter(
                post=self.object.id, status=COMMENT_STATUS_APPROVED
            ).select_related()
        }

        return super(BlogDetailView, self).get_context_data(**context)

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response with a template depending if the request is ajax
        or not and it renders with the given context.
        """
        if self.request.is_ajax():
            template = self.page_template
        else:
            template = self.get_template_names()

        return self.response_class(
            request=self.request,
            template=template,
            context=context,
            **response_kwargs
        )

speedyblog/templates/speedyblog/post_detail.html
{% extends 'base.djhtml' %}
{% load markdown_deux_tags %}

{% block page_title %}{{ post.get_meta_title }}{% endblock %}
{% block og_title %}{{ post.get_meta_title }}{% endblock %}
{% block twitter_title %}{{ post.get_meta_title }}{% endblock %}

{% block meta_description %}{{ post.get_meta_description|striptags|truncatewords:27 }}{% endblock %}
{% block og_description %}{{ post.get_meta_description|striptags|truncatewords:27 }}{% endblock %}
{% block twitter_description %}{{ post.get_meta_description|striptags|truncatewords:27 }}{% endblock %}

{% block content %}
<div class="main blog blog-detail">
    <div class="main-inner">
        <div class="container mt-4">
            <ol class="breadcrumb">
                <li class="separator">
                    <a href="{% url 'portal:portal-home' %}">
                        Home
                    </a>
                </li>
                <li class="separator">
                    <a href="{% url 'speedyblog:blog_index' %}">Blog</a>
                </li>
                <li class="separator">
                    <a href="{{ post.category.get_absolute_url }}">{{ post.category.name }}</a>
                </li>
                <li>
                    {{ post.title }}
                </li>
            </ol>
            <div class="row">
                <div class="col-md-8 col-lg-9">
                    <h1>{{ post.title }}</h1>
                    <div class="content">
                        <div class="post-detail">
                            {% if post.image %}
                                <img alt="" class="img-fluid mb-4" src="{{ post.image }}" /><br />
                            {% endif %}

                            <div class="item-detail">
                                {{ post.description|markdown }}
                            </div>
                            <hr class="mb-4" />

                            {% if post.allow_comments %}
                                {% if post.get_comments_count %}
                                <h2>{{ post.get_comments_count }} comments in this topic</h2>
                                {% endif %}

                                {% include page_template %}

                                {% include 'speedyblog/includes/post_form.html' %}
                            {% else %}
                            <p>
                                Comments are disabled for this post.
                            </p>
                            {% endif %}
                            <!-- /.comment-create -->
                        </div>
                        <!-- /.post-detail -->
                    </div>
                    <!-- /.content -->
                </div>
                <!-- /.col-* -->
                <div class="col-md-4 col-lg-3">
                    {% include 'speedyblog/includes/sidebar.html' %}
                </div>
                <!-- /.col-* -->
            </div>
            <!-- /.row -->
        </div>

    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

speedyblog/templates/speedyblog/post_detail_page.html
{% load el_pagination_tags %}
{% load markdown_deux_tags %}


{% if comments %}
	{% paginate comments %}
	{% for comment in comments %}
		<ul class="comments">
		    <li>
		        <div class="comment">
		            <div class="comment-author">
		                <a href="#" style="background-image: url('/static/img/tmp/agent-1.jpg');">
		                </a>
		            </div>
		            <!-- /.comment-author -->
		            <div class="comment-content">
		                <div class="comment-meta">
		                    <div class="comment-meta-author">
		                        Posted by {{ comment.user_name }}
		                    </div>
		                    <div class="comment-meta-date">
		                        <span>
		                            {{ comment.created_on|date:'d M, Y' }}
		                        </span>
		                    </div>
		                </div>
		                <!-- /.comment -->
		                <div class="comment-body">
		                    {{ comment.comment|markdown }}
		                </div>
		                <!-- /.comment-body -->
		            </div>
		            <!-- /.comment-content -->
		        </div>
		        <!-- /.comment -->
		    </li>
		</ul>

	{% endfor %}

	{% show_more "Load more comments" %}

{% endif %}

speedyblog/templates/speedyblog/post_list_page.html
{% extends 'base.djhtml' %}
{% load el_pagination_tags %}
{% load markdown_deux_tags %}

{% block page_title %}{% if selected_category %}{{ selected_category.get_meta_title }}{% else %}Ideal Spaces Blog - Read Startups Tips & Advice{% endif %}{% endblock %}
{% block og_title %}{% if selected_category %}{{ selected_category.get_meta_title }}{% else %}Ideal Spaces Blog - Read Startups Tips & Advice{% endif %}{% endblock %}
{% block twitter_title %}{% if selected_category %}{{ selected_category.get_meta_title }}{% else %}Ideal Spaces Blog - Read Startups Tips & Advice{% endif %}{% endblock %}
{% block meta_description %}{% if selected_category %}{{ selected_category.get_meta_description }}{% else %}Tips and Advice to grow your business and doing business in UAE. Read tips, advice and inspiration from the Ideal Spaces rock stars!{% endif %}{% endblock %}
{% block og_description %}{% if selected_category %}{{ selected_category.get_meta_description }}{% else %}Tips and Advice to grow your business and doing business in UAE. Read tips, advice and inspiration from the Ideal Spaces rock stars!{% endif %}{% endblock %}
{% block twitter_description %}{% if selected_category %}{{ selected_category.get_meta_description }}{% else %}Tips and Advice to grow your business and doing business in UAE. Read tips, advice and inspiration from the Ideal Spaces rock stars!{% endif %}{% endblock %}


{% block content %}

<div class="main blog blog-list">
    <div class="main-inner">
        <div class="container mt-4">
            <ol class="breadcrumb">
                <li class="separator">
                    <a href="{% url 'portal:portal-home' %}">
                        Home
                    </a>
                </li>
                {% if selected_category %}
                <li class="separator">
                    <a href="{% url 'speedyblog:blog_index' %}" class="active">Blogs</a>
                </li>
                <li>{{ selected_category }}</li>
                {% else %}
                <li>
                    <a href="{% url 'speedyblog:blog_index' %}" class="active">Blogs</a>
                </li>
                {% endif %}
            </ol>
            <div class="row has-sidebar">
                <div class="col-md-8 col-lg-9 col-xl-9">

                    <div class="posts">
                    {% if posts %}
                        {% paginate posts %}

                        {% for post in posts %}
                            <div class="post">
                                <div class="post-date">
                                    <strong>{{ post.created_on|date:'d' }}</strong>
                                    <span>{{ post.created_on|date:'M' }}</span>
                                </div>
                                <div class="post-image">
                                    <a class="post-image-link" href="{{ post.get_absolute_url }}" style="background-image: url('{% if post.image %}{{ post.image }}{% else %}http://via.placeholder.com/440x310{% endif %}');">
                                    </a>
                                    <div class="post-author">
                                        <span class="post-author-image">
                                            <a href="{{ post.get_absolute_url }}" style="background-image:url({% if post.image %}{{ post.image }}{% else %}http://via.placeholder.com/440x310{% endif %});">
                                            </a>
                                        </span>
                                        <!-- /.post-author-image -->
                                        <a href="{{ post.get_absolute_url }}">
                                            <span class="post-author-name">{{ post.category.name }}</span>
                                        </a>
                                    </div>
                                    <!-- /.post-author -->
                                </div>
                                <!-- /.post-image -->
                                <div class="post-title">
                                    <h2>
                                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    </h2>
                                </div>
                                <!-- /.post-title -->
                                <div class="post-meta">
                                    <div class="post-meta-item">
                                        Posted by 
                                        <a href="{{ post.get_absolute_url }}">{{ post.posted_by }}</a>
                                    </div>
                                    <!-- /.post-meta-item -->
                                    <div class="post-meta-item">
                                        <i class="fa fa-calendar"></i>
                                        {{ post.updated_on|date:'d M, Y' }}
                                    </div>
                                    <!-- /.post-meta-item -->
                                    <div class="post-meta-item">
                                        <i class="fa fa-comment">
                                        </i>
                                        <a href="{{ post.get_absolute_url }}">{{ post.get_comments_count }} comments</a>
                                    </div>
                                    <!-- /.post-meta-item -->
                                </div>
                                <!-- /.post-meta -->
                                <div class="post-content">
                                    <p>{{ post.description|slice:":150" }}...</p>
                                </div>
                                <!-- /.post-content -->
                                <div class="post-read-more">
                                    <a href="{{ post.get_absolute_url }}">Read More <i class="fa fa-chevron-right"></i></a>
                                </div>
                                <!-- /.post-read-more -->
                            </div>
                        {% endfor %}
                    {% else %}
                        <br>
                        <p>There are no blog posts.</p>
                    {% endif %}
                    </div>
                </div>
                <div class="col-md-4 col-lg-3 col-xl-3">
                    {% include 'speedyblog/includes/sidebar.html' %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}