shapp/urls.py
"""shapp URL Configuration"""
from django.urls import path
from django.urls import include
from django.contrib import admin


urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('', include('portal.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('speedyblog.urls')),
    # Third party library
    path('s3direct/', include('s3direct.urls')),
    # path('admin/runas/', include('runas.urls')),
]

speedyblog/urls.py
from django.urls import re_path

from speedyblog.views import BlogCategoryView
from speedyblog.views import BlogDetailView
from speedyblog.views import BlogListView


app_name = "speedyblog"

urlpatterns = [
    re_path(
        r'^(?P<slug>[-_\w]+)/$',
        BlogDetailView.as_view(),
        name='blog_detail'
    ),
    re_path(r'^category/(?P<slug>[-_\w]+)/$', BlogCategoryView.as_view(), name='blog_category'),
    re_path(r'^$', BlogListView.as_view(), name='blog_index'),
]

speedyblog/models.py
from django.conf import settings
from django.urls import reverse

from django.db import models

from s3direct.fields import S3DirectField

from .settings import COMMENT_STATUS_PENDING, COMMENT_STATUS_APPROVED, COMMENT_STATUS_DELETED
from .settings import POST_STATUS_PUBLISHED, POST_STATUS_UNPUBLISHED, POST_STATUS_DRAFT


class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField()

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    meta_title = models.CharField(max_length=100, blank=True)
    meta_description = models.CharField(max_length=500, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_meta_title(self):
        return self.meta_title or self.name

    def get_meta_description(self):
        return self.meta_description

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }

        return reverse('speedyblog:blog_category', kwargs=kwargs)

    def get_posts_count(self):
        return Post.objects.filter(category=self, status=POST_STATUS_PUBLISHED).count()


class Post(models.Model):
    STATUSES = (
        (POST_STATUS_PUBLISHED, 'Published'),
        (POST_STATUS_UNPUBLISHED, 'Unpublished'),
        (POST_STATUS_DRAFT, 'Draft'),
    )

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    status = models.CharField(max_length=1, choices=STATUSES, default=POST_STATUS_PUBLISHED, db_index=True)

    image = S3DirectField(dest="user_assets", blank=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    meta_title = models.CharField(max_length=100, blank=True)
    meta_description = models.CharField(max_length=500, blank=True)

    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    allow_comments = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.title

    def get_meta_title(self):
        return self.meta_title or self.title

    def get_meta_description(self):
        return self.meta_description or self.description

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }

        return reverse('speedyblog:blog_detail', kwargs=kwargs)

    def get_comments_count(self):
        return Comment.objects.filter(post=self, status=COMMENT_STATUS_APPROVED).count()


class Comment(models.Model):
    STATUSES = (
        (COMMENT_STATUS_PENDING, 'Pending'),
        (COMMENT_STATUS_APPROVED, 'Approved'),
        (COMMENT_STATUS_DELETED, 'Deleted')
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()

    created_on = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField(default='0.0.0.0')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=50, default='anonymous')
    user_email = models.EmailField(blank=True)

    status = models.CharField(max_length=1, choices=STATUSES, default=COMMENT_STATUS_PENDING, db_index=True)

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        ordering = ['created_on']

speedyblog/forms.py
from django import forms

from speedyblog.models import Comment
from speedyblog.settings import SPEEDY_POST_MAX_LENGTH


class UserCommentForm(forms.ModelForm):
    comment = forms.CharField()

    class Meta:
        model = Comment
        fields = ["comment"]
        widgets = {
            'comment': forms.Textarea(attrs={'maxlength': SPEEDY_POST_MAX_LENGTH})
        }

    def clean_comment(self):
        comment = self.cleaned_data.get('comment')

        if comment:
            if not comment.strip():
                raise forms.ValidationError('Comment field is required.')

        return comment


class CommentForm(UserCommentForm):
    user_name = forms.CharField(label='Username')
    user_email = forms.EmailField(label='Email', required=False)

    class Meta:
        model = Comment
        fields = ("user_name", "user_email", "comment")
        widgets = {
            'comment': forms.Textarea(attrs={'maxlength': SPEEDY_POST_MAX_LENGTH})
        }

    def clean_user_name(self):
        user_name = self.cleaned_data.get('user_name')

        if user_name:
            if not user_name.strip():
                raise forms.ValidationError('Username is required.')

        return user_name

speedyblog/views.py
import requests

from django.http import Http404
from django.conf import settings
from django.urls import reverse
from django.shortcuts import redirect
from django.views.generic.dates import DateDetailView
from django.views.generic import TemplateView, DetailView

from speedyblog.forms import CommentForm
from speedyblog.models import Comment, Post, Category

from shapp.helpers import get_client_ip

from speedyblog.settings import COMMENT_STATUS_APPROVED, POST_STATUS_PUBLISHED


class BlogListView(TemplateView):
    template_name = 'speedyblog/post_list_page.html'

    def get_context_data(self, **kwargs):
        ctx = super(BlogListView, self).get_context_data(**kwargs)

        ctx['posts'] = Post.objects.filter(status=POST_STATUS_PUBLISHED).select_related().order_by('-created_on')
        ctx['categories'] = Category.objects.all().order_by('name')

        return ctx


class BlogCategoryView(TemplateView):
    template_name = 'speedyblog/post_list_page.html'

    def get_context_data(self, **kwargs):
        slug = kwargs['slug']
        try:
            category = Category.objects.get(slug=slug)
        except Category.DoesNotExists:
            raise Http404()

        ctx = super(BlogCategoryView, self).get_context_data(**kwargs)
        ctx['posts'] = Post.objects.filter(status=POST_STATUS_PUBLISHED, category=category).select_related()
        ctx['selected_category'] = category
        ctx['categories'] = Category.objects.all().order_by('name')

        return ctx


class BlogDetailView(DetailView):
    model = Post
    field_name = 'slug'
    page_template = "speedyblog/post_detail_page.html"

    def get_queryset(self):
        queryset = super(BlogDetailView, self).get_queryset()

        return queryset.select_related()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        post = self.object

        form = CommentForm(request.POST)

        context = self.get_context_data(object=post)
        context['comment_form'] = form

        if form.is_valid():

            if not self.verify_captcha(request):
                context['invalid_captcha'] = True
                return self.render_to_response(context)

            comment = form.save(commit=False)
            comment.post = post

            comment.ip = get_client_ip(request)
            comment.save()

            return redirect("{}?success=1".format(post.get_absolute_url()))

        return self.render_to_response(context)

    def verify_captcha(self, request):
        payload = {
            'response': request.POST['g-recaptcha-response'],
            'remoteip': get_client_ip(request),
            'secret': settings.CAPTCHA_SECRET_KEY
        }

        response = requests.post('https://www.google.com/recaptcha/api/siteverify', payload)

        if response.status_code == 200:
            response = response.json()
        else:
            return False

        return response['success']

    def get_context_data(self, **kwargs):
        form = CommentForm()

        context = {
            'page_template': self.page_template,
            'comment_form': form,
            'categories': Category.objects.all().order_by('name'),
            'post_url': '{}{}'.format(settings.BASE_URL, self.object.get_absolute_url()),
            'comments': Comment.objects.filter(
                post=self.object.id, status=COMMENT_STATUS_APPROVED
            ).select_related()
        }

        return super(BlogDetailView, self).get_context_data(**context)

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response with a template depending if the request is ajax
        or not and it renders with the given context.
        """
        if self.request.is_ajax():
            template = self.page_template
        else:
            template = self.get_template_names()

        return self.response_class(
            request=self.request,
            template=template,
            context=context,
            **response_kwargs
        )

speedyblog/templates/speedyblog/includes/post_form.html
{{ comment_form.media }}

{% if request.GET.success %}
    <div class="alert-message success">
        Thank you for your comment. We will publish it after moderation.
    </div>
{% else %}

<h2>Write Feedback</h2>
<br />
<div class="comment-create">
    <form action="" method="post">
        {% csrf_token %}
        <div class="comment-input-box" id="post-comment">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input class="form-control form-control-lg" name="user_name" id="id_user_name" placeholder="Your Name" type="text" value="{% if comment_form.user_name.value %}{{ comment_form.user_name.value }}{% endif %}" />
                        {% if comment_form.user_name.errors %}
                            {{ comment_form.user_name.errors }}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input class="form-control form-control-lg" id="id_user_email" name="user_email" placeholder="Your Email" type="email" value="{% if comment_form.user_email.value %}{{ comment_form.user_email.value }}{% endif %}" />
                        {% if comment_form.user_email.errors %}
                            {{ comment_form.user_email.errors }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="comment">
                    Comment
                </label>
                <textarea class="form-control form-control-lg" id="id_comment" name="comment" placeholder="Your Comment">{% if comment_form.comment.value %}{{ comment_form.comment.value }}{% endif %}</textarea>
                {% if comment_form.comment.errors %}
                    {{ comment_form.comment.errors }}
                {% endif %}
            </div>
            <div class="form-group">
                <div class="g-recaptcha" data-sitekey="6LelB7sUAAAAAC9ml-DXcIRrVIWT_deBZZhZ6CdQ"></div>
                {% if invalid_captcha %}
                <ul class="errorlist">
                    <li>Invalid Captcha</li>
                </ul>
                {% endif %}
            </div>
            <div class="form-group">
                <button class="btn btn-lg btn-primary" type="submit">Post Comment</button>
            </div>
        </div>
    </form>
</div>
{% endif %}

speedyblog/templates/speedyblog/includes/sidebar.html
{% load static %}
<div class="sidebar">
    <div class="widget">
        <h2 class="widgettitle">Categories</h2>
        {% if categories %}
            <ul class="menu nav nav-stacked">
            {% for category in categories %}
            <li class="nav-item{% if selected_category and selected_category == category %} active{% endif %}">
                <a href="{{ category.get_absolute_url }}" class="nav-link">
                    <i class="fa fa-chevron-right"></i> {{ category.name }}
                </a>
            </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No category found</p>
        {% endif %}
    </div>
</div>